"""Tests for `snnchat.coherence`: the unintroduced-entity rate (UER@200).

CPU only, and CI has no `data/` directory, so everything that needs
corpus text reads ONE committed fixture:

    tests/fixtures/chat_stories_uer.json

HOW THE FIXTURE WAS MADE, AND HOW IT WAS CHECKED
------------------------------------------------
`python scripts/chat/coherence_score.py --data-dir <data/chat> --write-fixture
tests/fixtures/chat_stories_uer.json`. It is the FIRST 120 conversations of
`data/chat/stories_topic.val.bin` that have both a `<|user|>` and a `<|bot|>`
turn, in file order, decoded with `ChatTokenizer.decode_visible`; nothing was
chosen or dropped by content, and each story is cut at its last sentence end at
or before 500 characters to keep the file small. The file records its source's
sha256. On 2026-09-21 the generator was re-run and reproduced the committed file
byte for byte, and five rows (0, 17, 43, 88, 119) were checked by a route that
does not share the generator's parser: the row's prompt and story were ENCODED
and the byte string `USER prompt EOT BOT story` was found exactly once in the raw
`.bin`.

WHAT IS WORTH READING HERE
--------------------------
An instrument nobody has tried to break is a number generator, so two of these
tests are about breaking it. `test_replace_alternate_sentences_raises_uer_*` is
the can-fail test: a mutation that deletes introductions must move the rate, by
a margin that was measured. `test_plain_interleave_is_not_detected_known_blindness`
pins the opposite: a mutation a reader would call WORSE leaves the rate where it
was. That test passing is not good news. It is there so the limit stays a
measured fact that a future change to the instrument has to confront, rather
than a sentence in a docstring.

The fixture readings asserted below (clean 3/120, replace-alternate 32/120,
interleave 2/120) are regenerated by running this file's `_readings()`; the
full-corpus counterparts are in `experiments/chat/_quality/coherence_v14.json`
under `corpus.mutations`.

Not part of the research protocol; no number here is a reported figure.
"""
from __future__ import annotations

import importlib.util
import json
import os
import statistics
import subprocess
import sys

import numpy as np
import pytest

from snnchat import coherence
from snnchat.coherence import anchored_topic, uer, unintroduced_entities
from snnchat.tokenizer import BOS, EOT, ChatTokenizer

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

_SPEC = importlib.util.spec_from_file_location(
    "coherence_score", os.path.join(REPO, "scripts", "chat", "coherence_score.py"))
scorer = importlib.util.module_from_spec(_SPEC)
_SPEC.loader.exec_module(scorer)
FIXTURE = os.path.join(REPO, "tests", "fixtures", "chat_stories_uer.json")

#: The mutation partner of fixture story `i` is story `(i + PARTNER) % n` -- the
#: same fixed offset `scripts/chat/coherence_score.py` uses on the full corpus, so
#: the fixture readings and the artifact's are the same experiment at two sizes.
PARTNER = 7


def _pad(text: str, to: int = 260) -> str:
    """`text` padded past the window with a sentence that contains no "the"."""
    filler = " She smiled and he smiled and they all sat down for a while."
    while len(text) < to:
        text += filler
    return text


def _stories() -> list[str]:
    with open(FIXTURE, encoding="utf-8") as fh:
        return [row["story"] for row in json.load(fh)["rows"]]


def _readings() -> dict[str, dict]:
    stories = _stories()
    n = len(stories)
    partner = [stories[(i + PARTNER) % n] for i in range(n)]
    pairs = list(zip(stories, partner, strict=True))
    return {
        "clean": uer(stories),
        "replace": uer([coherence.replace_alternate_sentences(a, b) for a, b in pairs]),
        "interleave": uer([coherence.interleave_sentences(a, b) for a, b in pairs]),
    }


# --------------------------------------------------------------------------
# hand cases: the rule itself
# --------------------------------------------------------------------------


def test_a_definite_subject_never_introduced_is_flagged():
    """The failure the instrument was built for, in its smallest form."""
    text = "Once upon a time there was a sheep. The pig was big."
    assert unintroduced_entities(text) == ["pig"]


def test_a_definite_subject_introduced_earlier_is_clean():
    text = "Once upon a time there was a pig. The pig was big."
    assert unintroduced_entities(text) == []


def test_an_entity_is_reported_once_and_in_order_of_appearance():
    """The second "The pig" has the first one before it: that IS an earlier
    occurrence, so one drifted entity is one entry however long it is dwelt on."""
    text = "There was a sheep. The pig was big. The cow was sad. The pig was pink."
    assert unintroduced_entities(text) == ["pig", "cow"]


def test_the_head_is_the_word_before_the_verb_not_a_modifier():
    text = "There was a girl. The big red ball was shiny."
    assert unintroduced_entities(text) == ["ball"]
    # ...and an introduced MODIFIER does not introduce the head.
    assert unintroduced_entities("There was a red hat. The red ball was shiny.") == ["ball"]


def test_plural_tolerance_runs_in_both_directions():
    """"a bird ... The birds were" and "two birds ... The bird was" are both
    introduced. The prototype looked the head up as written and so flagged the
    first of these."""
    assert unintroduced_entities("She saw a bird. The birds were loud.") == []
    assert unintroduced_entities("She saw two birds. The bird was loud.") == []
    assert unintroduced_entities("He saw a fox. The foxes were quick.") == []
    assert unintroduced_entities("He saw two foxes. The fox was quick.") == []


def test_plural_tolerance_is_whole_word_not_substring():
    """"cat" inside "catalog" or "scatter" introduces nothing."""
    assert unintroduced_entities("She read a catalog. The cat was soft.") == ["cat"]
    assert unintroduced_entities("Leaves scatter. The cat was soft.") == ["cat"]


def test_an_object_definite_is_not_a_subject():
    """"went to the park" is a bridging definite in object position, which
    English does not require an introduction for. No verb follows it."""
    assert unintroduced_entities("Tim went to the park. He kicked the ball.") == []


def test_function_words_are_never_heads():
    """The prototype's first defect: its commonest corpus "entity" was "and"."""
    assert unintroduced_entities("Tim took the hat and went home.") == []
    assert unintroduced_entities("She liked the box because it was red.") == []
    assert unintroduced_entities("He saw the dog that they had fed.") == []
    # With the stoplist off, the defect is back -- which is what makes the
    # stoplist's effect a measurement and not a claim.
    assert unintroduced_entities("Tim took the hat and went home.", stoplist=False) == ["and"]


def test_unique_reference_nouns_are_never_heads():
    """"The sun was shining" introduces nothing and needs no introduction."""
    text = "One day the sun was bright. The sky was blue and the wind was soft."
    assert unintroduced_entities(text) == []
    assert unintroduced_entities(text, stoplist=False) == ["sun", "sky", "wind"]


def test_a_noun_phrase_does_not_span_a_conjunction():
    """Why the stoplist bars MODIFIERS inside the pattern, not just heads after it.

    "the [box and] Tim was" is not a noun phrase: "Tim" is the subject of the
    next clause and needs no introduction. A filter on the returned head could
    not reject it -- "tim" is not a function word -- so the bar has to sit on
    the modifier. The subject after the conjunction is still read when it is a
    definite of its own.
    """
    text = "There was a boy. He opened the box and Tim was glad."
    assert unintroduced_entities(text) == []
    assert unintroduced_entities(text, stoplist=False) == ["tim"]
    text = "There was a boy. He dropped the hat and the dog was sad."
    assert unintroduced_entities(text) == ["dog"]


def test_the_window_is_respected():
    """Only a subject that ENDS inside the window counts."""
    lead = _pad("There was a sheep.", 210)
    text = lead + " The pig was big."
    assert len(lead) >= 200
    assert unintroduced_entities(text) == []
    assert unintroduced_entities(text, window=len(text)) == ["pig"]
    # And one that ends exactly at the window edge is inside it.
    head = "There was a sheep. The pig was"
    assert unintroduced_entities(head + " big.", window=len(head)) == ["pig"]
    assert unintroduced_entities(head + " big.", window=len(head) - 1) == []


def test_a_verb_is_not_recognised_in_the_prefix_of_a_cut_word():
    """Why the pattern runs over the whole text and is cut afterwards.

    Cut at "The pig was|hing", `text[:window]` ends in "was" and a pattern run
    over the cut string would see a story verb that the text does not contain.
    """
    text = "There was a sheep. The pig washing itself smiled."
    cut = text.index("washing") + 3
    assert text[:cut].endswith("The pig was")
    assert unintroduced_entities(text, window=cut) == []


def test_context_counts_as_introduced_and_is_off_by_default():
    reply = "The pig was big. The cow was sad."
    assert unintroduced_entities(reply) == ["pig", "cow"]
    assert unintroduced_entities(reply, context="tell me a story about a pig") == ["cow"]
    assert unintroduced_entities(reply, context="tell me a story about pigs") == ["cow"]


# --------------------------------------------------------------------------
# uer: the rate, its denominator, and who qualifies
# --------------------------------------------------------------------------


def test_uer_counts_only_qualifying_texts_and_reports_the_fraction():
    """The fixed window is what stops a shorter-reply arm winning by length, so
    a short text must leave the DENOMINATOR, not be scored over less text."""
    drift = _pad("There was a sheep. The pig was big.")
    clean = _pad("There was a pig. The pig was big.")
    short_drift = "There was a sheep. The pig was big."
    assert len(short_drift) < 200 <= min(len(drift), len(clean))

    r = uer([drift, clean, clean, short_drift, short_drift])
    assert (r["k"], r["n"], r["n_total"]) == (1, 3, 5)
    assert r["rate"] == pytest.approx(1 / 3)
    assert r["qualifying_fraction"] == pytest.approx(3 / 5)
    assert r["window"] == 200
    assert set(r) == {"rate", "k", "n", "ci", "qualifying_fraction", "n_total", "window"}
    lo, hi = r["ci"]
    assert 0.0 <= lo < r["rate"] < hi <= 1.0


def test_uer_qualifying_boundary_is_len_at_least_window():
    text = _pad("There was a sheep. The pig was big.")
    assert uer([text[:200]])["n"] == 1
    assert uer([text[:199]])["n"] == 0
    assert uer([text[:199]], window=199)["n"] == 1


def test_uer_with_nothing_qualifying_is_no_measurement_not_a_perfect_score():
    r = uer(["The pig was big."])
    assert r["rate"] is None and (r["k"], r["n"], r["n_total"]) == (0, 0, 1)
    assert r["ci"] == [0.0, 1.0]
    assert r["qualifying_fraction"] == 0.0
    empty = uer([])
    assert empty["rate"] is None and empty["qualifying_fraction"] is None


def test_uer_counts_texts_not_entities():
    """k is replies with AT LEAST ONE unintroduced entity, never a sum of them."""
    two = _pad("There was a sheep. The pig was big. The cow was sad.")
    assert len(unintroduced_entities(two)) == 2
    assert uer([two])["k"] == 1


def test_uer_accepts_a_generator_and_checks_contexts_length():
    text = _pad("The pig was big.")
    assert uer(t for t in [text])["k"] == 1
    assert uer([text], contexts=["a story about a pig"])["k"] == 0
    with pytest.raises(ValueError, match="one prompt per text"):
        uer([text, text], contexts=["a story about a pig"])


def test_wilson_interval_matches_the_conventions_worked_example():
    """`docs/chat/CONVENTIONS.md` §1: 6/48 -> [0.059, 0.247]. The interval is
    inlined in `coherence` because `snnchat.quality` imports torch, so it is
    checked against the documented value rather than against that function."""
    lo, hi = coherence.wilson_interval(6, 48)
    assert lo == pytest.approx(0.0586, abs=5e-4)
    assert hi == pytest.approx(0.247, abs=5e-4)
    assert coherence.wilson_interval(0, 0) == (0.0, 1.0)
    lo0, hi0 = coherence.wilson_interval(0, 50)
    assert lo0 == 0.0 and 0.0 < hi0 < 0.1


# --------------------------------------------------------------------------
# the fixture, and the two mutations
# --------------------------------------------------------------------------


def test_fixture_is_what_it_claims():
    with open(FIXTURE, encoding="utf-8") as fh:
        doc = json.load(fh)
    rows = doc["rows"]
    assert doc["n"] == len(rows) and 60 <= len(rows) <= 120
    assert os.path.getsize(FIXTURE) < 80_000
    assert all(len(r["story"]) >= coherence.WINDOW for r in rows)
    assert all(r["prompt"] and r["story"][-1] in ".!?\"'" for r in rows)
    assert len({r["story"] for r in rows}) == len(rows)
    assert len(doc["source_sha256"]) == 64 and "stories_topic.val.bin" in doc["source"]


def test_mutations_do_what_their_names_say():
    a = "A one. A two. A three. A four. A five."
    b = "B one. B two. B three."
    assert coherence.split_sentences(a) == ["A one.", "A two.", "A three.", "A four.", "A five."]
    # Odd indices come from `b` while `b` lasts; the length stays `a`'s.
    assert coherence.replace_alternate_sentences(a, b) == "A one. B two. A three. A four. A five."
    assert coherence.interleave_sentences(a, b) == "A one. B one. A two. B two. A three. B three."


def test_replace_alternate_sentences_raises_uer_by_a_clear_margin():
    """CAN-FAIL. Deleting introductions while keeping the references to them is
    the shape of the model's drift, and if the instrument does not move under it
    the instrument measures nothing.

    Measured on the fixture (2026-09-21): clean 3/120 = 0.025, replace-alternate
    32/120 = 0.267 -- 29 more flagged stories. The bars below leave slack (20 of
    the 29; a rate ratio of 5 against the measured 10.7) and additionally demand
    that the two Wilson intervals do not overlap, so the test cannot be passed
    by a change that leaves the instrument merely noisy. Every mutant still
    qualifies, so the rise is not a change of denominator.
    """
    r = _readings()
    clean, replace = r["clean"], r["replace"]
    assert clean["n"] == replace["n"] == clean["n_total"] == 120
    assert replace["k"] - clean["k"] >= 20
    assert replace["rate"] >= 5 * clean["rate"]
    assert replace["ci"][0] > clean["ci"][1]
    # The clean corpus is near its floor: the instrument is not simply firing
    # on everything.
    assert clean["rate"] <= 0.06


def test_plain_interleave_is_not_detected_known_blindness():
    """DOCUMENTED BLINDNESS -- a known limit being pinned, NOT a desired property.

    Two complete stories shuffled sentence by sentence (A1, B1, A2, B2, ...) are
    less coherent to a reader than either mutant above, and UER reads them as
    CLEAN: nothing was deleted, so each story still introduces its own entities
    with "a" before it says "the". Measured on the fixture (2026-09-21):
    interleave 2/120 = 0.017 against clean 3/120 = 0.025 -- it reads BELOW the
    clean text, because the window now holds half as much of each story. The
    full corpus reference says the same (`coherence_v14.json`,
    `corpus.mutations.interleave`).

    If this test ever FAILS because the interleave rate rose, that is an
    improvement to the instrument, not a regression: update the module
    docstring's "WHAT IT CANNOT SEE" item 1 and this test together. Until then
    nobody may quote a low UER as evidence that a reply holds together.
    """
    r = _readings()
    assert r["interleave"]["n"] == 120
    assert r["interleave"]["rate"] <= r["clean"]["rate"] + 0.02
    # The contrast with the detected mutation, on the same pairs.
    assert r["interleave"]["rate"] < 0.25 * r["replace"]["rate"]


# --------------------------------------------------------------------------
# anchored_topic
# --------------------------------------------------------------------------


def test_anchored_topic_needs_an_introduction_and_a_second_mention():
    story = "Once upon a time there was a little brown penguin. The penguin was very fit."
    assert anchored_topic(story, "penguin")
    # Mentioned in passing at the end of a drifting story: a bare-mention hit,
    # not an anchored one.
    drift = "There was a sheep. The pig was very big. Then the penguin was very fit."
    assert not anchored_topic(drift, "penguin")
    # Introduced but never referred back to.
    assert not anchored_topic("There was a penguin. The pig was big.", "penguin")
    # Twice, but neither introduced with a/an nor in the first sentence.
    twice = "There was a sheep. The penguin was big. The penguin was fit."
    assert not anchored_topic(twice, "penguin")


def test_anchored_topic_first_sentence_and_plurals():
    # No a/an, but in the first sentence: anchored.
    assert anchored_topic("Penguins are fun. One penguin was very fit.", "penguin")
    assert anchored_topic("She had an apple. The apples were red.", "apples")
    # Whole word only, in the anchor and in the count of mentions alike.
    assert not anchored_topic("A catalog is a catalog.", "cat")
    assert not anchored_topic("There was a cat. She read the catalog.", "cat")


# --------------------------------------------------------------------------
# the purity contract
# --------------------------------------------------------------------------


def test_importing_coherence_does_not_import_torch():
    """In a fresh interpreter, because this process has torch loaded already.

    `json.dumps` embeds the path: the repository path contains an apostrophe.
    numpy is held to the same bar -- the module promises pure Python.
    """
    src = json.dumps(os.path.join(REPO, "src"))
    code = (
        f"import sys; sys.path.insert(0, {src}); import snnchat.coherence; "
        "bad = [m for m in ('torch', 'numpy', 'snnchat.rerank', 'snnchat.quality') "
        "if m in sys.modules]; print(bad); sys.exit(1 if bad else 0)"
    )
    out = subprocess.run(
        [sys.executable, "-c", code], capture_output=True, text=True, cwd=REPO, timeout=120
    )
    assert out.returncode == 0, out.stdout + out.stderr


# --------------------------------------------------------------------------
# scripts/chat/coherence_score.py
# --------------------------------------------------------------------------

QUALITY = os.path.join(REPO, "experiments", "chat", "_quality")


def test_story_turns_pairs_each_bot_turn_with_its_prompt_and_skips_narratives(tmp_path):
    """The corpus reference is "the turns the model is trained to produce as
    replies", so a bare narrative (BOS, text, EOT, no role markers) is not one,
    and a prompt must never leak across a conversation boundary."""
    tok = ChatTokenizer()
    ids = tok.render_conversation([("user", "a story about a pig"), ("bot", "There was a pig.")])
    ids += [BOS, *tok.encode("Once there was a narrative.").tolist(), EOT]
    ids += tok.render_conversation([("user", "one"), ("bot", "First."),
                                    ("user", "two"), ("bot", "Second.")])
    # A bot turn with no user turn in its own conversation has no prompt.
    ids += tok.render_conversation([("bot", "Orphan.")])
    path = tmp_path / "toy.bin"
    np.asarray(ids, dtype=np.uint8).tofile(path)
    assert scorer.story_turns(path) == [
        ("a story about a pig", "There was a pig."), ("one", "First."), ("two", "Second."),
    ]


def test_pool_files_reads_the_three_probe_lists_and_not_the_dodge_battery(tmp_path):
    for name in ("v12_heldout_chat-x.json", "v12_fresh_chat-x-s1.json", "v12_wide_chat-x.json",
                 "v12_dodge_chat-x.json", "v13_fresh_chat-x.json", "coherence_v14.json"):
        (tmp_path / name).write_text("{}", encoding="utf-8")
    assert [(a, b) for a, b, _ in scorer.pool_files(tmp_path)] == [
        ("fresh", "chat-x-s1"), ("heldout", "chat-x"), ("wide", "chat-x"),
    ]


def _toy_pool_file(path, flagged: int, clean: int) -> None:
    drift = _pad("There was a sheep. The pig was big.")
    fine = _pad("There was a pig. The pig was big.")
    pool = [{"text": drift}] * flagged + [{"text": fine}] * clean + [{"text": "Too short."}]
    row = {"prompt": "tell me a story about a pig", "pool": pool,
           "echo_text": drift, "base_text": fine}
    path.write_text(json.dumps({"ckpt": "toy", "probe_set": "toy", "rows": [row]}),
                    encoding="utf-8")


def test_file_section_scores_pool_and_selected_and_refuses_a_window_past_the_truncation(tmp_path):
    path = tmp_path / "v12_fresh_toy.json"
    _toy_pool_file(path, flagged=3, clean=5)
    sec = scorer.file_section(path, 200)
    assert (sec["pool"]["k"], sec["pool"]["n"], sec["pool"]["n_total"]) == (3, 8, 9)
    # The prompt introduced the pig, so with the prompt as context nothing is flagged.
    assert sec["pool_prompt_as_context"]["k"] == 0
    assert (sec["selected"]["k"], sec["selected"]["n"]) == (1, 1)
    assert (sec["score_only_selected"]["k"], sec["score_only_selected"]["n"]) == (0, 1)
    # echo_text is stored cut to 300 characters: a wider window would score the
    # selected column over less text than the pool, so it is refused, not scored.
    wide = scorer.file_section(path, 301)
    assert wide["selected"] is None and "300" in wide["selected_refused"]
    assert wide["pool"]["window"] == 301


def test_seed_section_sums_k_and_n_per_seed_and_takes_a_sample_sd(tmp_path):
    """A seed's rate pools its lists by SUMMING k and n (never a mean of rates,
    which would weight a 10-reply list like a 1000-reply one), a recipe is the
    run name with `-sN` removed, and SD_seed is the sample SD (ddof = 1)."""
    spec = {
        "v12_fresh_chat-r.json": (1, 9), "v12_wide_chat-r.json": (18, 2),
        "v12_fresh_chat-r-s1.json": (2, 8),
        "v12_fresh_chat-r-s2.json": (4, 6),
        "v12_fresh_chat-other.json": (0, 10),
    }
    for name, (flagged, clean) in spec.items():
        _toy_pool_file(tmp_path / name, flagged, clean)
    index = scorer.pool_files(tmp_path)
    files = {p.name: scorer.file_section(p, 200) for _, _, p in index}
    out = scorer.seed_section(files, index)
    assert set(out) == {"chat-r", "chat-other"}
    pool = out["chat-r"]["pool"]
    assert pool["n_seeds"] == 3
    assert (pool["per_seed"]["chat-r"]["k"], pool["per_seed"]["chat-r"]["n"]) == (19, 30)
    # 19/30, not the 0.5 that averaging the two lists' rates (0.1, 0.9) gives.
    rates = [19 / 30, 2 / 10, 4 / 10]
    assert pool["mean"] == pytest.approx(statistics.fmean(rates), abs=1e-6)
    assert pool["sd_seed"] == pytest.approx(statistics.stdev(rates), abs=1e-6)
    assert out["chat-other"]["pool"]["sd_seed"] is None     # one seed has no spread


def test_committed_artifact_is_what_the_instrument_says_about_a_committed_pool():
    """`coherence_v14.json` must trace to the committed draws AND to this tree's
    instrument. Anyone who changes a stoplist or the pattern and does not re-run
    `scripts/chat/coherence_score.py` turns this red -- which is the point: the
    artifact describes one instrument, and it has to be the one in `src/`.
    (The corpus half of the artifact cannot be held the same way: CI has no
    `data/`. The fixture tests above are its stand-in.)"""
    with open(os.path.join(QUALITY, "coherence_v14.json"), encoding="utf-8") as fh:
        artifact = json.load(fh)
    assert artifact["instrument"] == "unintroduced-entity rate (UER@200)"
    name = "v12_fresh_chat-v3d-aligned.json"
    fresh = scorer.file_section(scorer.Path(QUALITY) / name, artifact["window"])
    assert fresh == artifact["files"][name]
    # All 24 echo_holdout-format files are in it, and the incumbent's four
    # training seeds are what SD_seed was taken over.
    assert sorted(artifact["files"]) == [p.name for _, _, p in scorer.pool_files(
        scorer.Path(QUALITY))]
    incumbent = artifact["across_training_seeds"]["chat-v3d-aligned"]
    assert incumbent["seeds"] == ["chat-v3d-aligned", "chat-v3d-aligned-s1",
                                  "chat-v3d-aligned-s2", "chat-v3d-aligned-s3"]
    rates = [v["rate"] for v in incumbent["pool"]["per_seed"].values()]
    assert incumbent["pool"]["n_seeds"] == 4
    assert incumbent["pool"]["sd_seed"] == pytest.approx(statistics.stdev(rates), abs=1e-5)
